### ISSUE TITLE
Incorrect links on contributors page

### ISSUE THREAD

**Issue by vkhramtsov** [symfony/symfony-marketing#142] opened 2014-02-20 05:46 UTC
Go to page http://symfony.com/contributors/code (http://symfony.com/contributors/doc) and scroll down to users with position number 100 and lower.  Some of these records leads to https://connect.sensiolabs.com. All links for these users are broken and leads us to login page of https://connect.sensiolabs.com. For top 99 users everything is ok.

**Comment by javiereguiluz** [comment] 2015-08-18 13:12
@vkhramtsov thanks for reporting this error. I've just tested it again and I cannot reproduce the error. The links for the users outside the Top100 are slightly different, but they work right. For example, in this screenshot you can see the link I get when putting the mouse in the user number 104:

![top_100_users](https://cloud.githubusercontent.com/assets/73419/9330740/69d67daa-45bb-11e5-92ef-dc31cc3c516b.png)

If you can reproduce the error in any way or have more information, please reopen this issue. Thanks!

**Comment by OskarStark** [comment] 2015-08-18 14:04
@javiereguiluz are you logged out or in?

**Comment by javiereguiluz** [comment] 2015-08-18 14:25
@OskarStark I was logged in. I can now confirm the error. I've reopened this issue and I will take care of it soon. Thanks!

**Comment by OskarStark** [comment] 2015-08-18 14:26
you're welcome @javiereguiluz 
thank you for reopening this issue

**Comment by javiereguiluz** [comment] 2015-08-20 14:18
The fix has been deployed.

**Closed by javiereguiluz** 2015-08-20 14:18 UTC
Labels: Bug, hasPR
